### ISSUE TITLE
TypeError: Cannot read property 'profile_pic_url_hd' of undefined

### ISSUE THREAD

**Issue by ahmetcanaksu** [CodeDotJS/instagram-profile-picture#1] opened 2018-03-14 21:54 UTC
I got this error .

TypeError: Cannot read property 'profile_pic_url_hd' of undefined
    at got.then.res (C:\Users\ahmet\node_modules\instagram-profile-picture\index.js:31:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by CodeDotJS** [comment] 2018-03-16 16:28
Hi, 

Instagram has done some changes and that's causing this problem. I'll fix it as soon as possible. Thanks for reporting the issue. 

I'm keeping it open so that I don't forget to fix it.

**Comment by CodeDotJS** [comment] 2018-03-20 07:38
Hi, The issue is fixed now! 

Just update the package using `$ npm install --save instagram-profile-picture` and everything will work as it's mentioned in the readme!

**Closed as completed by CodeDotJS** 2018-03-20 07:38 UTC
